# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pubmed_lib',
                'doc_host': 'https://Dmaturana81.github.io',
                'git_url': 'https://github.com/Dmaturana81/pubmed_lib',
                'lib_path': 'pubmed_lib'},
  'syms': {'pubmed_lib.core': {'pubmed_lib.core.foo': ('core.html#foo', 'pubmed_lib/core.py')}}}