# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_parser.ipynb.

# %% auto 0
__all__ = ['regex', 'reg_email', 'db_name', 'parse_paperinfo', 'parse_author_xml', 'parsePubmedData', 'parseArticle',
           'parse_email', 'parseMayorKeys', 'parseMeshKeys']

# %% ../nbs/01_parser.ipynb 3
from Bio import Entrez
import sys
import pandas as pd
import xlsxwriter
from datetime import datetime, timedelta, date
from collections import defaultdict, Counter
import  pickle
from fastcore.all import *
from dotenv import load_dotenv


# %% ../nbs/01_parser.ipynb 5
regex = re.compile(("([a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`"
                    "{|}~-]+)*(@|\sat\s)(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?(\.|"
                    "\sdot\s))+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)"))
reg_email = re.compile("[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$")
db_name = ''

# %% ../nbs/01_parser.ipynb 6
def parse_paperinfo(
    paperinfo_xml:str #Information 
    ):
    """
    :param paperinfo_xml:
    :return:
    """
    PubmedData = parsePubmedData(paperinfo_xml['PubmedData'])
    article_xml = parseArticle(paperinfo_xml['MedlineCitation']['Article'])
    mayorKeys, (mayorMeshKeys, minorMeshKeys) = parseKeys(paperinfo_xml['MedlineCitation'])
    article_xml['mayorKeys'] = mayorKeys
    article_xml['mayorMesh'] = mayorMeshKeys
    article_xml['minorMesh'] = minorMeshKeys
    try:
        autorlist = []
        for author_xml in article_xml['autorlist']:
            if author_xml.attributes['ValidYN'] == 'N':
                continue
            autor_dict = parse_author_xml(author_xml)
            if autor_dict is None:
                continue
            autorlist.append(autor_dict)
            # article_xml['autorlist'][i] = autor_dict
    except:
        print('ERROR: parsing author {}'.format(author_xml))
    finally:
        article_xml['autorlist'] = autorlist
        PubmedData.update(article_xml)
    return PubmedData
    

# %% ../nbs/01_parser.ipynb 7
def parse_author_xml(autor_xml):
    """
    (dict)->dict
    Receive un diccionario con las informaciones de autor proveniente de pubmed xml article

    :param autor_xml:
    :return:
    """
    # Return false if no author information found
    if 'CollectiveName' in autor_xml:
        return
    # try to parse information from XML
    try:
        #get Identifier (only orcid is used now so if they have identifier it should be the first value
        if len(autor_xml['Identifier']) > 0:
            autorID = autor_xml['Identifier'][0]
        else:
            autorID = ''
        #Get the affilaition details from that author, if he had
        if len(autor_xml['AffiliationInfo']) > 0:
            AFFs = ';'.join([affiliationinfo['Affiliation'] for affiliationinfo in autor_xml['AffiliationInfo']])
        else:
            AFFs = ''
        #Retrieving the name information, it is a must and should exist
        autorFN = autor_xml['ForeName']
        autorLN = autor_xml['LastName']
        autorIN = autor_xml['Initials']
        name = autorFN + ' ' + autorLN

        #Start parsing or retrieving information for country, email, company, institute from affiliation
        country_name, state = find_country(AFFs)
        emails = parse_email(AFFs)
        data = {'Fname': autorFN, 'Lname': autorLN, 'emails': emails, 'affiliations': AFFs, 'countries': country_name,
                'identifier': autorID, 'name': name, 'n_papers': 0, 'updated': date.today().strftime('%d-%m-%Y'),
                'state': state, 'initials': autorIN}
        return data

    except ValueError:
        print('not possible to get info value error')
        return
    except OSError as err:
        print("OS Error: {0}".format(err))
        return
    except:
        print('error en parsing')
        return

# %% ../nbs/01_parser.ipynb 8
def parsePubmedData(pubmeddata):
    """
    Receive the xml section of PubmedData and return list of ids
    :param pubmeddata:
    :return:
    """
    # accepted = {x.attributes['PubStatus']: x['Year'] for x in pubmeddata['History']}
    # print(accepted)
    ids = {x.attributes['IdType']: str(x) for x in pubmeddata['ArticleIdList']}
    # print(ids)
    # accepted.update(ids)
    return ids

# %% ../nbs/01_parser.ipynb 9
def parseArticle(article_info):
    """

    :param article_info: dictionary from key Article of an Medline citation
    :return (dict): tuple of dictionary with information from paper and autors
    """
    # Extract information about paper content
    title = article_info['ArticleTitle']
    journal = article_info['Journal']['Title']
    published_date = article_info['Journal']['JournalIssue']['PubDate']
    if 'Year' in published_date:
        published = published_date['Year']
    elif 'MedlineDate' in published_date:
        try:
            published = re.findall(r'\d\d\d\d',published_date['MedlineDate'])[0]
        except:
            published = published_date['MedlineDate'][:4]
    try:
#         print(article_info)
        abstract = '. '.join(article_info['Abstract']['AbstractText'])
    except:
        abstract = ''
    try:
        autorlist = article_info['AuthorList']
    except:
        print('no autors found, jumping next')
        autorlist = []
    return {'abstract': abstract, 'autorlist': autorlist, 'title': title, 'journal': journal,
            'published':published}

# %% ../nbs/01_parser.ipynb 10
def parse_email(affil_text):

    """
    Find email from given string
    :param affil_text:
    :return str:
    """
    match = re.search(r'[\w.-]+@[\w.-]+', affil_text)
    if match is not None:
        email = match.group()
        email = email.strip('.;,')
    else:
        email = ''
    return email

# %% ../nbs/01_parser.ipynb 11
def parseMayorKeys(citationInfo):
    keywordList = citationInfo['KeywordList']
    
    if len(keywordList) == 0:
        (mayorMesh, minorMesh) = parseMeshKeys(citationInfo)
        mayorMesh.extend(minorMesh)
        keys = mayorMesh
    else:
        keys = [str(x) for x in keywordList[0] if x.attributes['MajorTopicYN'] == 'Y']
        # keys.extend(mayorMesh)
        # keys.extend(minorMesh)
    return keys

# def parseMayorKeys(citationInfo):
#     keywordList = citationInfo['KeywordList']
#     if len(keywordList) == 0:
#         return []
#     else:
#         return [str(x) for x in keywordList[0] if x.attributes['MajorTopicYN'] == 'Y']

# %% ../nbs/01_parser.ipynb 12
def parseMeshKeys(citationInfo):
    if 'MeshHeadingList' not in citationInfo.keys():
        return [], []
    meshKeys = citationInfo['MeshHeadingList']
    mayorkeys = [str(x['DescriptorName']) for x in meshKeys if x['DescriptorName'].attributes['MajorTopicYN']=='Y']
    minorKeys = [str(x['DescriptorName']) for x in meshKeys if x['DescriptorName'].attributes['MajorTopicYN']=='N']
    for x in [mayorkeys, minorKeys]:
        if x is None:
            x = []
    return mayorkeys, minorKeys

# %% ../nbs/01_parser.ipynb 13
# def parseMeshKeys(citationInfo):
#     if 'MeshHeadingList' not in citationInfo.keys():
#         return [], []
#     meshKeys = citationInfo['MeshHeadingList']
#     mayorkeys = [str(x['DescriptorName']) for x in meshKeys if x['DescriptorName'].attributes['MajorTopicYN']=='Y']
#     minorKeys = [str(x['DescriptorName']) for x in meshKeys if x['DescriptorName'].attributes['MajorTopicYN']=='N']
#     return mayorkeys, minorKeys
